//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThemeMeUp.Mobile.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThemeMeUp.Mobile.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anime.
        /// </summary>
        public static string AnimeLabel {
            get {
                return ResourceManager.GetString("AnimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filters.
        /// </summary>
        public static string ApplyFiltersLabel {
            get {
                return ResourceManager.GetString("ApplyFiltersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string CategoriesLabel {
            get {
                return ResourceManager.GetString("CategoriesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string FavoritesLabel {
            get {
                return ResourceManager.GetString("FavoritesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string FiltersLabel {
            get {
                return ResourceManager.GetString("FiltersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralLabel {
            get {
                return ResourceManager.GetString("GeneralLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General settings.
        /// </summary>
        public static string GeneralSettingsLabel {
            get {
                return ResourceManager.GetString("GeneralSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string LatestLabel {
            get {
                return ResourceManager.GetString("LatestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load full image in preview.
        /// </summary>
        public static string LoadFullImageInPreviewLabel {
            get {
                return ResourceManager.GetString("LoadFullImageInPreviewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a wallpaper to get more information.
        /// </summary>
        public static string MainPageFooterLabel {
            get {
                return ResourceManager.GetString("MainPageFooterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No token found.
        /// </summary>
        public static string NoTokenFoundLabel {
            get {
                return ResourceManager.GetString("NoTokenFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSFW.
        /// </summary>
        public static string NsfwLabel {
            get {
                return ResourceManager.GetString("NsfwLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string PeopleLabel {
            get {
                return ResourceManager.GetString("PeopleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string ProcessingLabel {
            get {
                return ResourceManager.GetString("ProcessingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purity.
        /// </summary>
        public static string PurityLabel {
            get {
                return ResourceManager.GetString("PurityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set token.
        /// </summary>
        public static string SetTokenLabel {
            get {
                return ResourceManager.GetString("SetTokenLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SFW.
        /// </summary>
        public static string SfwLabel {
            get {
                return ResourceManager.GetString("SfwLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketchy.
        /// </summary>
        public static string SketchyLabel {
            get {
                return ResourceManager.GetString("SketchyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorting.
        /// </summary>
        public static string SortingLabel {
            get {
                return ResourceManager.GetString("SortingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token added.
        /// </summary>
        public static string TokenAddedLabel {
            get {
                return ResourceManager.GetString("TokenAddedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top (1 day).
        /// </summary>
        public static string TopOneDayLabel {
            get {
                return ResourceManager.GetString("TopOneDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top (1 month).
        /// </summary>
        public static string TopOneMonthLabel {
            get {
                return ResourceManager.GetString("TopOneMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top (1 week).
        /// </summary>
        public static string TopOneWeekLabel {
            get {
                return ResourceManager.GetString("TopOneWeekLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top (1 year).
        /// </summary>
        public static string TopOneYearLabel {
            get {
                return ResourceManager.GetString("TopOneYearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top (6 month).
        /// </summary>
        public static string TopSixMonthLabel {
            get {
                return ResourceManager.GetString("TopSixMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top (3 days).
        /// </summary>
        public static string TopThreeDayLabel {
            get {
                return ResourceManager.GetString("TopThreeDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top (3 month).
        /// </summary>
        public static string TopThreeMonthLabel {
            get {
                return ResourceManager.GetString("TopThreeMonthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string ViewsLabel {
            get {
                return ResourceManager.GetString("ViewsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallhaven settings.
        /// </summary>
        public static string WallhavenSettingsLabel {
            get {
                return ResourceManager.GetString("WallhavenSettingsLabel", resourceCulture);
            }
        }
    }
}
